### ISSUE TITLE
Issues after testing

### ISSUE THREAD

**Issue by Lotx-001** [kisapilot/openpilot#7]
Greetings,

Thank you for accepting my assistance. You’ve made significant changes, and I'm grateful for your support in making my KIA K8 GL3 supported. However, I've noticed some features aren't functioning properly، while basic features work perfectly on highways, there are issues I'd like to address for a smoother experience:

1. Experimental mode & longitudinal are not working and show "Harness Malfunction check hardware" when activated.

2. HDA doesn't appear on the car dashboard.

3. Auto slowing on curves isn't working, despite setting the option to "Dist&Curv."

I appreciate your patience and would like to work together to resolve these issues for an improved driving experience.

Many thanks,
Lotx-001

**Comment by multikyd** [comment]
1. K8 GL3 is canfd. Basically canfd experimental long is not supported for now. I have difficulties to test canfd cars dont own.
2. HDA icon on the dashboard can show. But no realdata and test result. this is not a big deal.
3. This feature is related to VC(Variable Cruise) so it hasnt be tested yet for CANFD cars and not included in the code of canfd part.
